- 005_GUJJARI.SUPRIYA_contribution/program1.py
- 005_GUJJARI.SUPRIYA_contribution/program10.py
- 005_GUJJARI.SUPRIYA_contribution/program2.py
- 005_GUJJARI.SUPRIYA_contribution/program3.py
- 005_GUJJARI.SUPRIYA_contribution/program4.py
- 005_GUJJARI.SUPRIYA_contribution/program5.py
- 005_GUJJARI.SUPRIYA_contribution/program6.py
- 005_GUJJARI.SUPRIYA_contribution/program7.py
- 005_GUJJARI.SUPRIYA_contribution/program8.py
- 005_GUJJARI.SUPRIYA_contribution/program9.py
basic_python_assignments(20-june-2022)
> 005_GUJJARI.SUPRIYA_contribution

- 035_ Naziya_contributions/first_file.py
> 024_Naziya _contributions

- 024_anithagujjari_contribution/solution1.py
- 024_anithagujjari_contribution/solution10.py
- 024_anithagujjari_contribution/solution2.py
- 024_anithagujjari_contribution/solution3.py
- 024_anithagujjari_contribution/solution4.py
- 024_anithagujjari_contribution/solution5.py
- 024_anithagujjari_contribution/solution6.py
- 024_anithagujjari_contribution/solution7.py
- 024_anithagujjari_contribution/solution8.py
- 024_anithagujjari_contribution/solution9.py
> 024_anithagujjari_contribution

- 04_Ranga sai kiran/#print fibanacoo series.py
- 04_Ranga sai kiran/042_sai kiran ranga _contribution.py
> 041_sai kiran ranga_contribution

- 006_Shruti_Reddi_contributions/Exercise11.py
- 006_Shruti_Reddi_contributions/Exercise12.py
- 006_Shruti_Reddi_contributions/Exercise13.py
- 006_Shruti_Reddi_contributions/Exercise14.py
- 006_Shruti_Reddi_contributions/exercise10p1.py
- 006_Shruti_Reddi_contributions/exercise10p2.py
> Updation of Exercises

- 046_Siddi_Likhit_manohar_contributions/assign_q1.py
- 046_Siddi_Likhit_manohar_contributions/assign_q2.py
- assign_q1.py
> 046_Siddi_Likhit_manohar_contributions

- 047_Dinesh_Ramesh_contributions
> Assignment_1

- 035_ naziya_contributions/Assignment 2.py
- 035_ naziya_contributions/Assignment3.py
- 035_ naziya_contributions/Assignment8.py
- 035_ naziya_contributions/Exercise_1.py
- 035_ naziya_contributions/assignment 4.py
- 035_ naziya_contributions/practice.py
> 035_naziya_contributions

- add.py
- calculator.py
- multiply.py
- output.txt
Question1_Solution_KarpagaNanthini
> Solution_KarpagaNanthini

- 003_Vamsi_Rajavarapu_contributions/Caculator.py
Assignment----1st program 
[Calculator.zip](https://github.com/saikrishnavadali05/SSSSO-RR-District-Basic-Python-Training-June-2022/files/9175495/Calculator.zip)
> Calculator.py

- Birthday.py
[Uploading Birthday.zip…]()
Assignment -----2nd program
> Birthday.py

- may_2025_contributions/PY-M-27_Venkatapuram_Sai_Srujan_Contributions/Sai_Srujan.txt.txt
Sai Ram - Added Sai Srujan text File
> PY-M-27_Venkatapuram_Sai_Srujan_Contributions 

- may_2025_contributions/PY-F-102_divyasreetalari_submission/hello.py
I have created a folder for assignment submition with a sample file.
> created a folder with hello.py sample file

- may_2025_folder/PY-F-94_LikithaNarukulla_submissions/sample.txt
Added sample.txt file in may_2025_contributions/PY-F-94_LikithaNarukulla_submission folder as per your instructions
> PY-F-94 LikithaNarukulla submission

- may_2025_contributions/PY-F-112_Sneha_P_submission/Intro.py
A short introduction about myself
> My Introduction

- may_2025_contributions/PY-M-45_Saikumar/sample_program.py
> PY-M-45_saikumar

- may_2025_contributions/PY-M-33_Naveen/hello.py
> PY-M-33_Naveen

- may_2025_contributions/PY-M-32_Patnaik Sai Harsha Vardhan_submission/Introduction.txt
> PY-M-32_Patnaik Sai Harsha Vardhan_submission

- may_2025_contributions/PY-F-127_Ziya Samreen_submission/readme.md
Added my assignment folder inside may_2025_contributions as instructed. Kindly review and approve.
> Added assignment folder: PY-F-127_Ziya Samreen_submission

- may_2025_contributions/PY-M-14_Vivekanand Goud Varada_submission/python_basics_assignment.ipynb
> PY-M-14_Vivekanand Goud Varada_submission

- may_2025_contributions/PY-F-94_LikithaNarukulla_submissions/094_Likitha_Narukulla/A5_Assignment/A5Q10_words_more_than_4.py
- may_2025_contributions/PY-F-94_LikithaNarukulla_submissions/094_Likitha_Narukulla/A5_Assignment/A5Q1_reverse_string.py
- may_2025_contributions/PY-F-94_LikithaNarukulla_submissions/094_Likitha_Narukulla/A5_Assignment/A5Q2_check_digits.py
- may_2025_contributions/PY-F-94_LikithaNarukulla_submissions/094_Likitha_Narukulla/A5_Assignment/A5Q3_replace_spaces.py
- may_2025_contributions/PY-F-94_LikithaNarukulla_submissions/094_Likitha_Narukulla/A5_Assignment/A5Q4_capitalize_title.py
- may_2025_contributions/PY-F-94_LikithaNarukulla_submissions/094_Likitha_Narukulla/A5_Assignment/A5Q5_compare_strings.py
- may_2025_contributions/PY-F-94_LikithaNarukulla_submissions/094_Likitha_Narukulla/A5_Assignment/A5Q6_split_on_comma.py
- may_2025_contributions/PY-F-94_LikithaNarukulla_submissions/094_Likitha_Narukulla/A5_Assignment/A5Q7_remove_punctuation.py
- may_2025_contributions/PY-F-94_LikithaNarukulla_submissions/094_Likitha_Narukulla/A5_Assignment/A5Q8_extract_domain.py
- may_2025_contributions/PY-F-94_LikithaNarukulla_submissions/094_Likitha_Narukulla/A5_Assignment/A5Q9_starts_vowel_ends_consonant.py
[Indexing]
[Object Identity]
[Built-in Functions]
[String Methods]
[Formatting with f-strings]
[Slicing Operator]
[Helper Strings]
[Important String Operations]
> assignment 5 

- may_2025_contributions/PY-M-14_Vivekanand Goud Varada_submission/Data_types_&_variables_assignment.ipynb
> data_types_&_variables_assignment uploaded

- may_2025_contributions/PY-M-27_Venkatapuram_Sai_Srujan_Submissions/Assign2.py
- may_2025_contributions/PY-M-27_Venkatapuram_Sai_Srujan_Submissions/The_Whisper_of_File_Modes.txt
- may_2025_contributions/PY-M-27_Venkatapuram_Sai_Srujan_Submissions/Week-2-Assignments/escape_sequences/alarm.py
- may_2025_contributions/PY-M-27_Venkatapuram_Sai_Srujan_Submissions/Week-2-Assignments/escape_sequences/clock.py
- may_2025_contributions/PY-M-27_Venkatapuram_Sai_Srujan_Submissions/Week-2-Assignments/escape_sequences/escape.ipynb
- may_2025_contributions/PY-M-27_Venkatapuram_Sai_Srujan_Submissions/Week-2-Assignments/escape_sequences/replace.py
- may_2025_contributions/PY-M-27_Venkatapuram_Sai_Srujan_Submissions/Week-2-Assignments/strings/string_format.py
- may_2025_contributions/PY-M-27_Venkatapuram_Sai_Srujan_Submissions/Week-2-Assignments/strings/strings.ipynb
> Added Week -2 Assignment

- may_2025_contributions/PY-M-53_E. V. S. SAI RAM_Submission/MiniProject/miniproject_QuizApplication.ipynb
- may_2025_contributions/PY-M-53_E. V. S. SAI RAM_Submission/MiniProject/miniproject_QuizApplication.py
- may_2025_contributions/PY-M-53_E. V. S. SAI RAM_Submission/MiniProject/quiz.json
- may_2025_contributions/PY-M-53_E. V. S. SAI RAM_Submission/miniproject_QuizApplication.ipynb
This is a python code done in jupyter for reading questions and answers from json file. Prompt user to enter answer by showing question and then shows result
> MiniProject - QuizApplication

- may_2025_contributions/PY_F_136_Manushree_Adla_submissions/app.py
- may_2025_contributions/PY_F_136_Manushree_Adla_submissions/expenses.csv
- may_2025_contributions/PY_F_136_Manushree_Adla_submissions/index.html
- may_2025_contributions/PY_F_136_Manushree_Adla_submissions/mini-project-styles.css
> Mini Project Submission

- Age calculator1.ipynb
> Age Calculator

- 115_Mini_project/word.css
- 115_Mini_project/word.js
- 115_Mini_project/word.python.py
- 115_Mini_project/wordpuzzle.html
- may_2025_contributions/python_mini_project/app.py
- may_2025_contributions/python_mini_project/static/style.css
- may_2025_contributions/python_mini_project/templates/index.html
- may_2025_contributions/python_mini_project/words.txt
integrated flask to my mini project
> word_scramble_game 
